'use strict';

var jargon = [
    "Deploying Cross-Media Relationships",
    "Targeting User-Centric Eyeballs",
    "Maximizing World-Class Markets",
    "Recontextualizing Turn-Key Experiences",
    "Strategizing Vertical Infomediaries",
    "Enabling Next-Generation Systems",
    "Delivering Leading-Edge Users",
    "Orchestrating Transparent Metrics",
    "Exploiting Value-Added Paradigms",
    "Unleashing Front-End Synergies",
    "Driving Real-Time E-Commerce",
    "Visualizing Distributed Solutions",
    "Transforming Intuitive Communities",
    "Synergizing Killer Channels",
    "Aggregating Open-Source Niches",
    "Productizing Cross-Platform Platforms",
    "Incentivizing Efficient Models",
    "Engaging One-to-One Networks",
    "Engineering Global Architectures",
    "Embracing Visionary Content",
    "Reinventing Synergistic Interfaces",
    "Extending Viral Web-Readiness",
    "Cultivating Dot-Com Portals",
    "Revolutionizing Dynamic Methodologies",
    "Streamlining Collaborative Deliverables",
    "Enhancing Holistic Technologies",
    "Utilizing Web-Enabled Bandwidth",
    "Repurposing Back-End ROI",
    "Implementing 24/7 Functionalities",
    "Synthesizing End-to-End Partnerships",
    "Integrating Seamless Mindshare",
    "Facilitating Virtual Supply-Chains",
    "Branding Compelling Web Services",
    "Matrixing Scalable E-Services",
    "Iterating Extensible Applications",
    "Scaling Integrated Infrastructures",
    "Growing Customized E-Markets",
    "Architecting Revolutionary Convergence",
    "Evolving Bleeding-Edge Schemas",
    "Monetizing Impactful E-Business",
    "Optimizing Wireless Initiatives",
    "Expediting Enterprise Vortals",
    "Whiteboarding Best-of-Breed E-Tailers",
    "Meshing Mission-Critical Action-Items"
];

angular.module('reticulatingSplines')
    .constant('webJargon', jargon);
